### ISSUE TITLE
Question: CSS @define-colors/ @define-drawables

### ISSUE THREAD

**Issue by saaadel** [dayllenger/beamui#9]
просто пытаюсь разобраться - зачем ты используешь дополнительные at-rules CSS: @define-colors, @define-drawables ?

почему не использовать обычный CSS?

```css
DialogFrame {
    padding: 0;
    border: 1px solid #888;
    box-shadow: 0 4px 18px #555;
}

@define-colors {
    dialog_background: #eee;
}
```
вместо этого использовать
```css
DialogFrame {
    padding: 0;
    border: 1px solid #888;
    box-shadow: 0 4px 18px #555;
    background: #eee;
}
```
второй момент: если уже и использовать такие поля, то может стоит использовать для имен hyphen-case (через тире вместо подчеркивания)?
